### ISSUE TITLE
螢幕過小，下面推薦詞語撿字會變撿角

### ISSUE THREAD

**Issue by onemid** [fogdingding/dict_frontend#8]
螢幕過小的時候，下面的字會結歸丸

是在哈囉？

**Comment by fogdingding** [comment]
:)

**Comment by fogdingding** [comment]
感謝大哥

**Comment by onemid** [comment]
<div class="col-md-3">
                    <div class="alert alert-dark">
                        <div class="custom-control custom-checkbox">
                                <strong>
                                    <input type="checkbox" class="custom-control-input" value="${element[0]}" id="check${cnt}" name="recommend_check[]">
                                    <label class="custom-control-label" for="check${cnt}"> ${element[0]}</label>
                                </strong>
                                    <i class="far fa-star"></i> ${toDecimal(element[1])}
                        </div>
                    </div>
                </div>

**Comment by onemid** [comment]
直接取代你那個             msg.forEach(element => {
                $('#recommend_word_append').append(`...`);
裡面的 ...__

**Comment by fogdingding** [comment]
謝謝大哥

Gong, Yi-Jhong <notifications@github.com> 於 2019年11月29日 週五 下午10:44寫道：
